# Generated by Django 4.2.3 on 2023-08-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='users',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='users',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='users',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='users',
            name='segundo_nombre',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
