# Generated by Django 4.2.3 on 2023-08-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_users_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='direccion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='nombre_empresa',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
